{
  "testSteps" : [ {
    "Step_Number" : 1,
    "Step_Description" : "go to url",
    "Control_Type" : "WebElement",
    "Locator_Type" : "",
    "Locator_Value" : "",
    "User_Action" : "Go to url",
    "Data_Column" : "1",
    "Step_Property" : "text",
    "Step_Index" : "",
    "Step_Data" : "https://www.google.com/",
    "Screenshot_Enabled" : true,
    "Optional_Step_Enabled" : false,
    "Parameterized_Step_Enabled" : false,
    "Shadow_Step_Enabled" : false,
    "Is_Iterate_Step" : false,
    "Data_View_Type" : "text"
  }, {
    "Step_Number" : 2,
    "Step_Description" : "Execute test case",
    "Control_Type" : "WebElement",
    "Locator_Type" : "File upload",
    "Locator_Value" : "7a9a4ee7-9f6c-456a-b25c-832e07bc2c1d",
    "User_Action" : "Execute Test Case",
    "Data_Column" : "2",
    "Step_Property" : "text",
    "Step_Index" : "",
    "Step_Data" : "",
    "Screenshot_Enabled" : true,
    "Optional_Step_Enabled" : false,
    "Parameterized_Step_Enabled" : false,
    "Shadow_Step_Enabled" : false,
    "Is_Iterate_Step" : false,
    "Data_View_Type" : "text"
  }, {
    "Step_Number" : 3,
    "Step_Description" : "Execute function",
    "Control_Type" : "WebElement",
    "Locator_Type" : "Id",
    "Locator_Value" : "",
    "User_Action" : "Execute Function",
    "Data_Column" : "3",
    "Step_Property" : "text",
    "Step_Index" : "",
    "Step_Data" : "acccac50-2917-402f-a977-b5ea3dcfa15c",
    "Screenshot_Enabled" : true,
    "Optional_Step_Enabled" : false,
    "Parameterized_Step_Enabled" : false,
    "Shadow_Step_Enabled" : false,
    "Is_Iterate_Step" : false,
    "Data_View_Type" : "text"
  } ],
  "functionSteps" : [ {
    "Step_Number" : 1,
    "Step_Description" : "go to URL",
    "Control_Type" : "WebElement",
    "Locator_Type" : "",
    "Locator_Value" : "",
    "User_Action" : "Go to url",
    "Data_Column" : "1",
    "Step_Property" : "text",
    "Step_Index" : "",
    "Step_Data" : "https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_oncontextmenu_dom",
    "Screenshot_Enabled" : true,
    "Optional_Step_Enabled" : false,
    "Parameterized_Step_Enabled" : false,
    "Shadow_step_enabled" : false,
    "Test_Step_Number" : 3,
    "Data_View_Type" : "text"
  }, {
    "Step_Number" : 2,
    "Step_Description" : "wait",
    "Control_Type" : "WebElement",
    "Locator_Type" : "",
    "Locator_Value" : "",
    "User_Action" : "Wait",
    "Data_Column" : "2",
    "Step_Property" : "text",
    "Step_Index" : "",
    "Step_Data" : "4",
    "Screenshot_Enabled" : true,
    "Optional_Step_Enabled" : false,
    "Parameterized_Step_Enabled" : false,
    "Shadow_step_enabled" : false,
    "Test_Step_Number" : 3,
    "Data_View_Type" : "text"
  }, {
    "Step_Number" : 3,
    "Step_Description" : "right click",
    "Control_Type" : "WebElement",
    "Locator_Type" : "Xpath",
    "Locator_Value" : "//div[@id='div01']/*[text()='Right-click in this box to see the hidden content!']",
    "User_Action" : "Right Click",
    "Data_Column" : "3",
    "Step_Property" : "text",
    "Step_Index" : "",
    "Step_Data" : "",
    "Screenshot_Enabled" : true,
    "Optional_Step_Enabled" : false,
    "Parameterized_Step_Enabled" : false,
    "Shadow_step_enabled" : false,
    "Test_Step_Number" : 3,
    "Data_View_Type" : "text"
  }, {
    "Step_Number" : 4,
    "Step_Description" : "wait",
    "Control_Type" : "WebElement",
    "Locator_Type" : "",
    "Locator_Value" : "",
    "User_Action" : "Wait",
    "Data_Column" : "2",
    "Step_Property" : "text",
    "Step_Index" : "",
    "Step_Data" : "4",
    "Screenshot_Enabled" : true,
    "Optional_Step_Enabled" : false,
    "Parameterized_Step_Enabled" : false,
    "Shadow_step_enabled" : false,
    "Test_Step_Number" : 3,
    "Data_View_Type" : "text"
  }, {
    "Step_Number" : 5,
    "Step_Description" : "verify text",
    "Control_Type" : "WebElement",
    "Locator_Type" : "Xpath",
    "Locator_Value" : "(//div[@id='myDiv']/*[text()='This info is hidden'])[1]",
    "User_Action" : "Verify Text",
    "Data_Column" : "5",
    "Step_Property" : "text",
    "Step_Index" : "",
    "Step_Data" : "This info is hidden",
    "Screenshot_Enabled" : true,
    "Optional_Step_Enabled" : false,
    "Parameterized_Step_Enabled" : false,
    "Shadow_step_enabled" : false,
    "Test_Step_Number" : 3,
    "Data_View_Type" : "text"
  } ],
  "iterateData" : [ ]
}